version: "3"
volumes:
  pgsql_db:
    driver: local
  mysql_db:
    driver: local
services:
  mysql_db:
    build: ./mysql
    volumes:
      - mysql_db:/var/lib/mysql
    env_file:
      - ./mysql.env
    environment:
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
  pgsql_db:
    build: ./pgsql
    volumes:
      - pgsql_db:/var/lib/postgresql/data
    env_file:
      - ./pgsql.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: "Asia/Tokyo"
  web:
    image: akira345/php7app-dev:latest
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/web
    environment:
      MEMCACHED_HOST: "memcached_srv"
      DOCUMENT_ROOT: "/var/www/web/html"
    depends_on:
      - pgsql_db
      - mysql_db
      - memcached
    links:
      - pgsql_db:pgsql_db
      - mysql_db:mysql_db
      - mail:mail_srv
      - memcached:memcached_srv
  mail:
# Mail Cacherはポート1025でつなぎに行く
    image: pocari/mailcatcher
    ports:
      - "1080:1080"
  memcached:
    image: memcached:1.5
