version: "2"
volumes:
  pgsql_db:
    driver: local
  mysql_db:
    driver: local
services:
  mysql_db:
    build: ./mysql
    volumes:
      - mysql_db:/var/lib/mysql
    env_file:
      - ./mysql.env
    environment:
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
  pgsql_db:
    build: ./pgsql
    volumes:
      - pgsql_db:/var/lib/postgresql/data
    env_file:
      - ./pgsql.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: "Asia/Tokyo"
  web:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/web
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - pgsql_db
      - mysql_db
    links:
      - pgsql_db:pgsql_db
      - mysql_db:mysql_db
